// Generated by CoffeeScript 1.3.3
(function() {
  var ListViewModel;

  ListViewModel = function(model) {
    var _this = this;
    this.editing = ko.observable(false);
    this.newTaskTitle = ko.observable('');
    this.title = kb.observable(model, {
      key: 'title',
      write: (function(title) {
        if ($.trim(title)) {
          model.save({
            title: $.trim(title)
          });
        } else {
          _.defer(function() {
            return model.destroy();
          });
        }
        return _this.editing(false);
      })
    }, this);
    this.tasks = kb.collectionObservable(model.get('tasks'));
    this.editBegin = function() {
      _this.editing(true);
      return $('input.edit').focus();
    };
    this.editEnd = function(view_model, event) {
      if (event.keyCode === Trask.Keyboard.ENTER || event.type === 'blur') {
        return _this.editing(false);
      }
    };
    this.createTask = function(view_model, event) {
      var newTask;
      if (!$.trim(_this.newTaskTitle()) || event.keyCode !== Trask.Keyboard.ENTER) {
        return;
      }
      newTask = _this.tasks.collection().create({
        title: $.trim(_this.newTaskTitle()),
        belongsTo: model.get('id')
      });
      model.get('tasks').add(newTask);
      return Backbone.sync('update', model, {
        success: function() {
          return _this.newTaskTitle('');
        }
      });
    };
    this.slug = ko.computed(function() {
      return _this.title().toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, '');
    });
    return this;
  };

  window.ListsViewModel = function(lists) {
    var _this = this;
    this.title = ko.observable('');
    this.lists = kb.collectionObservable(lists, {
      view_model: ListViewModel
    });
    this.lists.collection().bind('change', function() {
      return _this.lists.valueHasMutated();
    });
    this.createList = function(view_model, event) {
      if (!$.trim(_this.title()) || (event.keyCode !== Trask.Keyboard.ENTER)) {
        return true;
      }
      lists.create({
        title: $.trim(_this.title()),
        tasks: new TaskCollection()
      });
      return _this.title('');
    };
    return this;
  };

}).call(this);
