// Generated by CoffeeScript 1.3.3
(function() {
  var ListViewModel;

  ListViewModel = function(model) {
    var _this = this;
    this.title = kb.observable(model, {
      key: 'title',
      write: (function(title) {
        if ($.trim(title)) {
          model.save({
            title: $.trim(title)
          });
        } else {
          _.defer(function() {
            return model.destroy();
          });
        }
        return _this.editing(false);
      })
    }, this);
    this.newTaskTitle = ko.observable('');
    this.tasks = new kb.collectionObservable(new TaskCollection());
    this.createTask = function(view_model, event) {
      if (!$.trim(_this.newTaskTitle()) || (event.keyCode !== trask.ENTER_KEY)) {
        return true;
      }
      _this.tasks.collection().create({
        title: $.trim(_this.newTaskTitle())
      });
      return _this.newTaskTitle('');
    };
    this.slug = ko.computed(function() {
      return _this.title().toLowerCase().replace(/\ /g, '-').replace(/[^\w-]+/g, '');
    });
    return this;
  };

  window.ListsViewModel = function(lists) {
    var _this = this;
    this.title = ko.observable('');
    this.lists = kb.collectionObservable(lists, {
      view_model: ListViewModel
    });
    this.lists.collection().bind('change', function() {
      return _this.lists.valueHasMutated();
    });
    this.createList = function(view_model, event) {
      if (!$.trim(_this.title()) || (event.keyCode !== trask.ENTER_KEY)) {
        return true;
      }
      lists.create({
        title: $.trim(_this.title())
      });
      return _this.title('');
    };
    return this;
  };

}).call(this);
