// Generated by CoffeeScript 1.3.3
(function() {

  window.TaskViewModel = function(model) {
    var _this = this;
    this.editing = ko.observable(false);
    this.completed = kb.observable(model, {
      key: 'completed',
      read: (function() {
        return model.completed();
      }),
      write: (function(completed) {
        return model.completed(completed);
      })
    }, this);
    this.title = kb.observable(model, {
      key: 'title',
      write: (function(title) {
        if ($.trim(title)) {
          model.save({
            title: $.trim(title)
          });
        } else {
          _.defer(function() {
            return model.destroy();
          });
        }
        return _this.editing(false);
      })
    }, this);
    this.editEnd = function(view_model, event) {
      if (event.keyCode === Trask.Keyboard.ENTER || event.type === 'blur') {
        return _this.editing(false);
      }
    };
    return this;
  };

}).call(this);
