#!/bin/bash

PIDFILE=".watch.pid"

touch $PIDFILE || (echo "Unable to write to .watch.pid" && exit 1)

# Kill off old processes
while read pid; do
	kill $pid
done < $PIDFILE

# Truncate the PID file
> $PIDFILE

# Store the PID of coffee and sass watch processes
coffee -o app/js/ -cw src/coffee/ > ./coffee-compile.log 2>&1 &
echo $! >> $PIDFILE

sass --watch src/sass:app/css > ./sass-compile.log 2>&1 &
echo $! >> $PIDFILE
