// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    Trask.Collections.Lists = new ListCollection();
    Trask.Collections.Lists.fetch();
    Trask.ViewModels.Lists = new ListsViewModel(Trask.Collections.Lists);
    Trask.ViewModels.Settings = new SettingsViewModel();
    ko.applyBindings(Trask.ViewModels, $('#trask')[0]);
    Trask.Router = new AppRouter();
    return Backbone.history.start();
  });

  $(function() {
    $(document).foundationAlerts();
    $(document).foundationButtons();
    $(document).foundationAccordion();
    $(document).foundationNavigation();
    $(document).foundationCustomForms();
    $(document).foundationMediaQueryViewer();
    $(document).foundationTabs({
      callback: $.foundation.customForms.appendCustomMarkup
    });
    $(document).tooltips();
    return $('input, textarea').placeholder();
  });

}).call(this);
