// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    window.trask = {
      viewmodels: {},
      collections: {}
    };
    trask.ENTER_KEY = 13;
    trask.collections.lists = new ListCollection();
    trask.collections.lists.fetch();
    trask.viewmodels.lists = new ListsViewModel(trask.collections.lists);
    trask.viewmodels.settings = new SettingsViewModel();
    ko.applyBindings(trask.viewmodels, $('#trask')[0]);
    new AppRouter();
    return Backbone.history.start();
  });

  $(function() {
    $(document).foundationAlerts();
    $(document).foundationButtons();
    $(document).foundationAccordion();
    $(document).foundationNavigation();
    $(document).foundationCustomForms();
    $(document).foundationMediaQueryViewer();
    $(document).foundationTabs({
      callback: $.foundation.customForms.appendCustomMarkup
    });
    $(document).tooltips();
    return $('input, textarea').placeholder();
  });

}).call(this);
