// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.List = (function(_super) {

    __extends(List, _super);

    function List() {
      return List.__super__.constructor.apply(this, arguments);
    }

    List.prototype.relations = [
      {
        type: Backbone.HasMany,
        key: 'tasks',
        relatedModel: 'Task',
        collectionType: 'TaskCollection',
        reverseRelation: {
          key: 'belongsTo'
        }
      }
    ];

    List.prototype.defaults = function() {
      return {
        created_at: new Date()
      };
    };

    return List;

  })(Backbone.RelationalModel);

  List.setup();

}).call(this);
