// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Task = (function(_super) {

    __extends(Task, _super);

    function Task() {
      return Task.__super__.constructor.apply(this, arguments);
    }

    Task.prototype.completed = function(completed) {
      if (arguments.length === 0) {
        return !!this.get('completed');
      }
      return this.save({
        completed: completed ? new Date() : null
      });
    };

    return Task;

  })(Backbone.RelationalModel);

  Task.setup();

}).call(this);
