// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TaskCollection = (function(_super) {

    __extends(TaskCollection, _super);

    function TaskCollection() {
      return TaskCollection.__super__.constructor.apply(this, arguments);
    }

    TaskCollection.prototype.model = Task;

    TaskCollection.prototype.localStorage = new Trask.Storage('tasks');

    return TaskCollection;

  })(Backbone.Collection);

}).call(this);
