// Generated by CoffeeScript 1.3.3
(function() {

  Trask.Storage = (function() {

    function Storage(storageKey) {
      return new Store('trask-' + storageKey);
    }

    return Storage;

  })();

}).call(this);
