// Generated by CoffeeScript 1.3.3
(function() {

  window.TraskStorage = (function() {

    function TraskStorage(storageKey) {
      return new Store('trask-' + storageKey);
    }

    return TraskStorage;

  })();

}).call(this);
